[package]
name = "clipable"
version = "0.1.0"
authors = ["rudes"]
edition = "2018"

[dependencies]
notify = "4.0.7"
windows-service = "0.1.0"
reqwest = "0.9.9"
serde = { version = "1.0.85", features = ["derive"] }
serde_json = "1.0.37"