[package]
name = "clipable"
version = "0.1.0"
authors = ["rudes"]
edition = "2018"

[dependencies]
winreg = "0.6.0"
notify = "4.0.7"
reqwest = "0.9.9"
serde_json = "1.0.37"
windows-service = "0.1.0"
serde = { version = "1.0.85", features = ["derive"] }